image: node:8

cache:
  paths:
  - node_modules/

stages:
  - build

pages:
  stage: build
  script:
   - npm install --silent
   - npm run build
  artifacts:
    paths:
     - public/

lint_js:
  stage: lint
  script:
    - npm install --silent eslint eslint-plugin-babel babel-eslint
    - ./node_modules/.bin/eslint .

lint_styles:
  stage: lint
  script:
    - npm install --silent stylelint stylelint-config-standard
    - ./node_modules/.bin/stylelint "**/*.scss"
